### PR TITLE
Make go get compatible

### PR DESCRIPTION
**Pull request by stevenh**
Added +build windows to all existing package source files.

Added go-get.go to base and oleutil directory which compiles for !windows so there is at least one file to compile.

### CODE REVIEW

**Comment by mattn** [comment]
Why you want this change? If you're using go-ole in non-windows environment, it is the very the mistake. I think.

**Comment by stevenh** [comment]
We use a none windows build machine as we target multiple oss with our app.
For this to work the package needs to be go get compatible.

I've successfully built our windows binary on our FreeBSD build machine
with this change and it works as expected.


On 27 Jan 2015, at 08:21, mattn <notifications@github.com> wrote:

Why you want this change? If you're using go-ole in non-windows
environment, it is the very the mistake. I think.

—
Reply to this email directly or view it on GitHub
<https://github.com/mattn/go-ole/pull/48#issuecomment-71607636>.

**Comment by mattn** [comment]
I believe there are your some codes that is using go-ole at least. Those files should be compile error. I'm thinking this problem will not be fixed even if I merge this.

**Comment by mattn** [comment]
I'm not sure, I guess you have a code using go-ole. (foo.go) you will fix this issue just to rename it to foo_windows.go.

**Comment by stevenh** [comment]
The part of our code which uses go-ole is indeed set to only build under windows, as you would expect, but the library still needs to be go get compatible to download.

You can see the use of // +build windows [in the popular winsvc package](https://code.google.com/p/winsvc/source/browse/svc/event.go), which is also windows only, for this very reason.

I can confirm that this patch does indeed allow code which uses your module in windows specific files, to compile and work on multiple platforms :)

This will also fix the outstanding issue [New issue
Cannot go get on Mac](https://github.com/mattn/go-ole/issues/47) as reported by @rubyenv

**Comment by mattn** [comment]
I'm guessing this may be a bug of go tool. I think go tool should not
get go-ole if the codes doesn't use it.

ping @minux how do you think?

On 1/27/15, Steven Hartland <notifications@github.com> wrote:
> The part of our code which uses go-ole is indeed set to only build under
> windows, as you would expect, but the library still needs to be go get
> compatible to download.
>
> You can see the use of // +build windows [in the popular winsvc
> package](https://code.google.com/p/winsvc/source/browse/svc/event.go), which
> is also windows only, for this very reason.
>
> I can confirm that this patch does indeed allow code which uses your module
> in windows specific files, to compile and work on multiple platforms :)
>
> This will also fix the outstanding issue [New issue
> Cannot go get on Mac](https://github.com/mattn/go-ole/issues/47) as reported
> by @rubyenv
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/go-ole/pull/48#issuecomment-71627686


-- 
- Yasuhiro Matsumoto

**Comment by minux** [comment]
what if you use GOOS=windows go get?

Anyway, you can use go get -d to download only.

**Comment by mjibson** [comment]
I completely agree that these files should have the windows build tag in them, exactly as the winsvc package does. Being able to go get this package, even when you are not on windows, is important. I had errors exactly as @stevenh describes with winsvc, and the build tags were added there. I believe our windows-only packages should follow that example and tag all our files as such.

The most correct thing is to tell go when you can't **build** your files, not to prevent them from being downloaded at all.

**Comment by mattn** [comment]
I created https://github.com/mattn/go-ole-test. And run as below on linux. I don't see any problem.

```
✔ mattn go get -u -x  github.com/mattn/go-ole-test
cd /home/mattn/dev/godev/src/github.com/mattn/go-ole-test
git remote -v
cd /home/mattn/dev/godev/src/github.com/mattn/go-ole-test
git symbolic-ref HEAD
cd /home/mattn/dev/godev/src/github.com/mattn/go-ole-test
git pull --ff-only
cd /home/mattn/dev/godev/src/github.com/mattn/go-ole-test
git show-ref
cd /home/mattn/dev/godev/src/github.com/mattn/go-ole-test
git checkout master
WORK=/tmp/go-build732969477
```

**Comment by jacobsantos** [comment]
Well, is the solution, so that you don't have to do *_windows.go?

**Comment by stevenh** [comment]
Nope

**Comment by jacobsantos** [comment]
Is this good @mattn?

**Comment by mattn** [comment]
okay, once I'll merge this PR, but I can't fully convinced.

**Comment by jacobsantos** [comment]
I don't know, I was thinking about setting up a Travis-CI go integration and seeing how it goes. Not sure what good it would do. Anyway, really I think part of the azure integration I might load up a Linux VM, compile and then move over to the Windows VM and see if it runs on 32-bit and 64-bit.

I'm going to revisit this and see. Might simply be better to use "go get" command to force downloading on Linux, but I don't know enough.

It is going to take a week to get intimate with C# and Interop, but once I do, I don't think it will take very long to get a COM server up and running. I want to complete the integration and do some documentation and testing.

I think I'm ready to finally finish my project from 2 years ago. Probably just going to make that open source.

**Pull request merged**
